---
- name: Update
  become: yes
  shell: "yum update -y"

- name: Install epel-release
  become: yes
  yum:
    name: epel-release
    state: present

- name: install python2-pip
  become: yes
  yum:
    name: python2-pip
    state: present
    
- name: Upgrade pip
  become: yes
  pip: name=pip state=latest
  tags:
    - packages

- name: Ensure botocore and boto3 modules are installed
  pip:
    name: [ "boto3", "botocore"]
    extra_args: "--user"

- name: Install python pip
  become: yes
  yum:
    name: python3-pip
    state: present
    update_cache: yes

- name: update python pip
  shell: "pip3 install --upgrade pip"

- name: Install ansible
  become: yes
  shell: "yum install -y ansible"
...