---
- name: Update
  shell: "yum update -y"

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install python pip
  yum:
    name: python3-pip
    state: present
    update_cache: yes

- name: update python pip
  shell: "pip3 install --upgrade pip"

- name: Install ansible
  shell: "yum install -y ansible"
...