---
- hosts: localhost
  gather_facts: no
  roles:
    - basics # Installation de Pytho, Ansible & liés
    - init_mainserv # Connexion à aws
#    - role: conf_instances
#      when: provides is defined
#  post_tasks:
#    - meta: refresh_inventory

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - basics
    - docker_install

- hosts: ansible_git_vpn
  become: yes
  become_method: sudo
  roles:
    - gitlab_install
    - openvpn_install # NON ACTIF POUR LE MOMENT

- hosts: apache_serv
  become: yes
  become_method: sudo
  roles:
    - httpd_install
    - # jekyll_install

- hosts: tomcat_serv
  become: yes
  become_method: sudo
  roles:
    - mysql_install
    - phpmyadmin_install
    - tomcat_install

- hosts: python_serv
  become: yes
  become_method: sudo
  roles:
...