---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - basics
    - init_mainserv
    - gitlab_install
    - role: conf_instances
      when: provides is defined
  post_tasks:
    - meta: refresh_inventory

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - basics
    - docker_install

- hosts: EpsiCorp_Jekyll
  become: yes
  become_method: sudo
  roles:
    - httpd_install

- hosts: EpsiCorp_Tomcat
  become: yes
  become_method: sudo
  roles:
    - tomcat_serv_install

- hosts: EpsiCorp_Python
  become: yes
  become_method: sudo
  roles:
    - jenkins_install
    - python_serv_install
...