---
inventory: "~/inventory.ini"

connection:
  account_private_key: "~/.ssh/aws_key_g1"
  private_key: "~/.ssh/aws_key_g1.pem"

aws:
  region: eu-central-1
  subnet_id: subnet-048068b0139ea48a8
  access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
  secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"

security_group:
  id: sg-0d99574644c9388ee

machines_groups:
  - name: EpsiCorp_Jekyll
    machines:
    - name: EpsiCorp_Jekyll
      image: ami-08b6d44b4f6f7b279
      type: t3.large
      count: 1

  - name: EpsiCorp_Tomcat
    machines:
    - name: EpsiCorp_Tomcat
      image: ami-08b6d44b4f6f7b279
      type: t3.large
      count: 1

  - name: EpsiCorp_Python
    machines:
    - name: EpsiCorp_Python
      image: ami-08b6d44b4f6f7b279
      type: t3.large
      count: 1

jenkins_image: jenkins/jenkins:lts
jenkins_port1: "8080"
jenkins_port2: "50000"
jenkins_dir: "/srv/jenkins"
...