---
# inventory: "~/inventory.ini"

connection:
  account_private_key: "~/.ssh/g1_aws_key"
  private_key: "~/.ssh/g1_aws_key.pem"

aws:
  region: eu-central-1
  subnet_id: subnet-XXXXX
  access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
  secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"

machines_groups:
  - name: jekyll
    machines:
    - name: G1_jekyll
      image: ami-08b6d44b4f6f7b279
      type: t3.large
      count: 1

  - name: tomcat
    machines:
    - name: G1_tomcat
      image: ami-08b6d44b4f6f7b279
      type: t3.large
      count: 1

  - name: python
    machines:
    - name: G1_python
      image: ami-08b6d44b4f6f7b279
      type: t3.large
      count: 1

mysql_dir1: "/srv/mysql/mysql"
mysql_dir2: "/srv/mysql/mysql-dump/"
port_mysql: "3306"

port_phpadmin: "8081"

tomcat_dir1: "/srv/tomcat/webapps/"
tomcat_dir2: "/srv/tomcat/conf"
port_tomcat: "8082"
...