---

# Installation du conteneur Gitlab Community Edition
- name: Installation de Gitlab CE 
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: yes
    recreate: yes
    privileged: yes
    exposed:
      - 443
      - 80
      - 22
    ports:
      - 443:443
      - 80:80
      - 22:22
    volumes:
      - /srv/gitlab/config:/etc/gitlab:Z
      - /srv/gitlab/logs:/var/log/gitlab:Z
      - /srv/gitlab/data:/var/opt/gitlab:Z

- name : Installation d'un runner Gitlab
  docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-ce:latest
    restart: yes
    recreate: yes
    volumes:
      - gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

- name: Enregistrement du runner
  command: "docker exec -it gitlab-runner gitlab-runner register --non-interactive \
--executor "docker" \
--docker-image alpine:latest \
--url "http://3.70.214.132/" \
--clone-url "http://3.70.214.132/" \
--registration-token "bvscxnydEoiz5Sunx22N" \
--description "docker-runner" \
--tag-list "docker,aws" \
--run-untagged="true" \
--locked="false" \
--access-level="not_protected""

...
