---
# Installation du conteneur Gitlab Community Edition
- name: Création du conteneur Gitlab CE
  command: "sudo docker run --detach \
--hostname 3.122.243.148 \
--publish 9343:443 --publish 9080:80 --publish 9222:22 \
--name gitlab \
--restart always \
--volume /srv/gitlab/config:/etc/gitlab:Z \
--volume /srv/gitlab/logs:/var/log/gitlab:Z \
--volume /srv/gitlab/data:/var/opt/gitlab:Z \
gitlab/gitlab-ce:latest"

- name: Installation d'un runner Gitlab
  command: "docker run -d --name gitlab-runner --restart always \
  -v gitlab-runner:/etc/gitlab-runner \
  -v /var/run/docker.sock:/var/run/docker.sock \
  gitlab/gitlab-runner:latest"

- name: Enregistrement du runner
  command: "docker exec -it gitlab-runner gitlab-runner register --non-interactive \
--executor "docker" \
--docker-image alpine:latest \
--url "http://3.127.236.112:9080/" \
--registration-token "87J75TMw-8rvjn7Qvz-x" \
--description "docker-runner" \
--tag-list "docker,aws" \
--run-untagged="true" \
--locked="false" \
--access-level="not_protected""
...
