---
- name: copy war file
  copy: 
    src: "target/"
    dest: "/srv/tomcat/webapps/"

- name: copy sql file
  copy: 
    src: "USER.sql"
    dest: "/srv/mysql/mysql-dump/"

- name: Install container mysql
#  become: yes
  docker_container:
    name: db
    image: mysql:5.7
    volumes:
       - "/srv/mysql/mysql:/var/lib/mysql"
       - "/srv/mysql/mysql-dump/:/docker-entrypoint-initdb.d"
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
    ports:
       - "3306:3306"

- name: chown mysql
  shell: 
    cmd: sudo docker exec db chown -R mysql:mysql /var/lib/mysql 

- name: Install container Phpadmin
#  become: yes
  docker_container:
    name: phpadmin
    image: phpmyadmin/phpmyadmin
    links: db
    ports:
      - "8081:80"
    env:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

- name: Install container tomcat
#  become: yes
  docker_container:
    name: tomcat
    image: tomcat
    links: db
    volumes:
      - "/srv/tomcat/webapps/:/usr/local/tomcat/webapps/"
    ports:
      - "8082:8080"
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
...