---
# Installation httpd et configuration du volume

- name: creation du volume website
  file:
    path: ./website
    state: directory
    owner: centos
    group: centos

- name: installation du conteneur httpd
  docker_container:
    name: httpd
    image: httpd:latest
    restart: yes
    recreate: yes
    ports:
      - 8080:80
    volumes:
      - ./website:/usr/local/apache2/htdocs

#- name: Demarrer le service httpd
#  service:
#    name: httpd 
#    state: started

...
